export const mockData = [
  {
    id: 1,
    name: "Bitcoin",
    shortName: "BTC",
    value: "0.1832",
    currency: "3880.63",
  },
  {
    id: 2,
    name: "Binance",
    shortName: "BUSD",
    value: "125.14",
    currency: "125.14",
  },
  {
    id: 3,
    name: "Ethereum",
    shortName: "ETH",
    value: "0.587",
    currency: "919.07",
  },
  {
    id: 4,
    name: "Ripple",
    shortName: "XRP",
    value: "12.356",
    currency: "4.82",
  },
  {
    id: 5,
    name: "Solana",
    shortName: "SOL",
    value: "0.999",
    currency: "23.15",
  },
  {
    id: 6,
    name: "Dogecoin",
    shortName: "DOGE",
    value: "7.504",
    currency: "1.50",
  },
  {
    id: 7,
    name: "Orchid",
    shortName: "OXT",
    value: "12.102",
    currency: "24.08",
  },
  { id: 8, name: "Tether", shortName: "USDT", value: "0.00", currency: "0.00" },
  {
    id: 9,
    name: "Solana",
    shortName: "SOL",
    value: "0.999",
    currency: "23.15",
  },
  {
    id: 10,
    name: "Solana",
    shortName: "SOL",
    value: "0.999",
    currency: "23.15",
  },
];
